### ISSUE TITLE
Is it support RethinkDB 2.2.1 ?

### ISSUE THREAD

**Issue by anand-singh** [fomkin/scala-reql#3]

**Comment by fomkin** [comment]
I wasn't tested it yet. New API it not implemented, but protocol is backward compatible so it should work. Note that this project is far away for production quality.

**Comment by anand-singh** [comment]
Thanks for reply. I am working on an interesting project and we are using RethinkDB but there are no drivers for Scala and Java.

Could you please suggest me a production ready driver for RethinkDB in Java or Scala

Thanks,
Anand

**Comment by fomkin** [comment]
As it appears official Java driver will be available soon 
https://github.com/rethinkdb/rethinkdb/tree/next/drivers/java

**Comment by anand-singh** [comment]
Thanks :+1:
